trigger:
- main

pool:
  name: Default   # Your agent pool name

variables:
  LT_USERNAME: 'devanshsingh'     # Replace with your LambdaTest username
  LT_ACCESS_KEY: 'LT_kjmzzJCYu70kReE7lwE0w2MOXLWg2q72EMh68BOot6fYI1c'     # Replace with your LambdaTest access key
  LT_BUILD_NAME: 'Test_Sample_Java'

steps:
# Step 1: Checkout the repository
- checkout: self

# Step 2: Run Maven commands
- script: |
    mvn clean install
    mvn clean test
  displayName: "Run Maven Build and Tests"
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)
    LT_BUILD_NAME: $(LT_BUILD_NAME)

# Step 3: Show LambdaTest Results
- task: LambdatestResults@1
  displayName: "LambdaTest Results"
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)
    LT_BUILD_NAME: $(LT_BUILD_NAME)
