trigger:
- main

pool:
  name: Default   # Your agent pool name

variables:
  LT_USERNAME: 'devanshsingh'     # Replace with your LambdaTest username
  LT_ACCESS_KEY: 'LT_kjmzzJCYu70kReE7lwE0w2MOXLWg2q72EMh68BOot6fYI1c'

steps:
  - task: Lambdatest.lambda-azure-pipeline-extention.configuration-task.configuration@1
    displayName: "LambdaTest configuration setup"
    env:
      LT_BUILD_NAME: Test_Sample_Java

  - script: |
      mvn clean install
      mvn clean test

    displayName: "Command Line Script"

  - task: Lambdatest.lambda-azure-pipeline-extention.showResults-task.LambdatestResults@1
    displayName: "Lambdatest Results"
    env:
      LT_BUILD_NAME: Test_Sample_Java
